# Generated by Django 4.0.5 on 2022-08-06 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_alter_user_is_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='creat_time',
            field=models.DateTimeField(default=datetime.date(2022, 8, 6)),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='user',
            table='t_user',
        ),
    ]
