# Generated by Django 4.0.5 on 2022-08-14 12:02

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaleChance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chanceSource', models.CharField(db_column='chance_source', max_length=300)),
                ('customerId', models.IntegerField(db_column='customer_id')),
                ('customerName', models.CharField(db_column='customer_name', max_length=100)),
                ('cgjv', models.IntegerField(db_column='cgjv')),
                ('overview', models.CharField(db_column='overview', max_length=300)),
                ('linkMan', models.CharField(db_column='link_man', max_length=20)),
                ('link_Phone', models.CharField(db_column='link_phone', max_length=20)),
                ('description', models.CharField(db_column='description', max_length=1000)),
                ('creatMan', models.CharField(db_column='create_man', max_length=20)),
                ('assignMan', models.CharField(db_column='assign_man', max_length=20)),
                ('assignTime', models.DateTimeField(auto_now_add=True, db_column='assign_time')),
                ('state', models.CharField(db_column='state', max_length=20)),
                ('devResult', models.CharField(db_column='dev_result', max_length=20)),
                ('is_Valid', models.IntegerField(db_column='is_valid')),
                ('createDate', models.DateTimeField(db_column='create_date')),
                ('updateDate', models.DateTimeField(db_column='update_date')),
            ],
            options={
                'db_table': 't_sale_chance',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CusDevPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planItem', models.CharField(db_column='plan_item', max_length=300)),
                ('planDate', models.DateTimeField(db_column='plan_date')),
                ('exeAffect', models.CharField(db_column='exe_affect', max_length=100)),
                ('isValid', models.IntegerField(db_column='is_valid')),
                ('createDate', models.DateTimeField(db_column='create_date')),
                ('updateDate', models.DateTimeField(db_column='update_date')),
                ('saleChance', models.ForeignKey(db_column='sale_chance_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='sales.salechance')),
            ],
            options={
                'db_table': 't_cus_dev_plan',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
